class_name GroundDetail
extends RefCounted
## Per-map helper textures for the ground/object shader (world.gdshader), built at load time from the bake:
##  - class_tex: one texel per map cell = which detail tile (res://assets/models/tiles/env_detail.png, generated by
##    pipeline/blender/env_textures.py) to lay over upstream's baked pixel ground there (grass blades, dirt pebbles,
##    pavement chips, wood grain ...). 255 = none, 254 = "auto": choose from the baked pixel's own colour, so the
##    ragged grass/path borders of upstream's painter get the right detail per pixel.
##  - ao_tex: soft contact-shadow mask (1 texel = 4 px of 2D art) of everything standing on the ground - buildings,
##    walls, trees, furniture, fences - the shader darkens the ground around their feet with it.

const T_GRASS := 0
const T_PATH := 1
const T_SAND := 2
const T_PAVE := 3
const T_ROCK := 4
const T_FLOOR := 5
const T_CARPET := 6
const T_WOOD := 7
const T_TOWER := 8
const T_WATER := 9
const T_CLIFF := 10
const NONE := 255
const AUTO := 254

const LABEL_CLASS := {
	"grass": AUTO, "tree": AUTO, "tree2": AUTO, "flowers": AUTO, "tall_grass": AUTO, "path_tufts": AUTO,
	"cut_tree": AUTO, "ledge_d": AUTO, "ledge_l": AUTO, "ledge_r": AUTO, "path": AUTO, "path_t": AUTO, "curb": AUTO,
	"fence": AUTO, "sign": AUTO, "sign_poke": AUTO, "sign_mart": AUTO, "sign_gym": AUTO, "cliff_top": AUTO,
	"roof_house": AUTO, "roof_flat": AUTO, "wall": AUTO, "window": AUTO, "door": AUTO,
	"sand": T_SAND, "pavement": T_PAVE, "bridge": T_WOOD, "cliff": T_CLIFF, "cave_ledge": T_CLIFF, "cave_wall": T_CLIFF,
	"cave_floor": T_ROCK, "cave_floor2": T_ROCK, "cave_high": T_ROCK, "cave_rock": T_ROCK, "cave_door": T_ROCK,
	"floor_tile": T_FLOOR, "floor": T_FLOOR, "floor_carpet": T_CARPET, "floor_tower": T_TOWER, "floor_stone": T_PAVE,
	"floor_dojo": T_WOOD, "ship_floor": T_WOOD, "deck": T_WOOD, "water": T_WATER,
}

## Interiors draw walls/pillars in 3D; the ground under them is whatever the room's floor is.
static func class_texture(bake: Dictionary) -> ImageTexture:
	var cw := int(bake.get("cw", 1))
	var ch := int(bake.get("ch", 1))
	var legend: Array = bake.get("legend", [])
	var labels: Array = bake.get("labels", [])
	var lut := PackedByteArray()
	lut.resize(maxi(1, legend.size()))
	for i in range(legend.size()):
		lut[i] = int(LABEL_CLASS.get(String(legend[i]), NONE))
	var data := PackedByteArray()
	data.resize(cw * ch)
	for i in range(mini(labels.size(), cw * ch)):
		data[i] = lut[int(labels[i])]
	var img := Image.create_from_data(cw, ch, false, Image.FORMAT_R8, data)
	return ImageTexture.create_from_image(img)

## Soft occlusion mask. Each block is reduced to the rectangle of ground it stands on.
static func ao_texture(bake: Dictionary) -> ImageTexture:
	var cw := int(bake.get("cw", 1))
	var ch := int(bake.get("ch", 1))
	var S := 4   # px of art per texel
	var w := cw * 16 / S
	var h := ch * 16 / S
	var img := Image.create(w, h, false, Image.FORMAT_R8)
	var one := Color(1, 1, 1, 1)
	for b in bake.get("blocks", []):
		var r := _foot(b)
		if r.size.x <= 0.0:
			continue
		if String(b.get("t", "")) == "cellboxes":
			for c in b.get("cells", []):
				_fill(img, Rect2(float(c[0]), float(c[1]), 16.0, 16.0), S, one)
		elif String(b.get("t", "")) == "walls":
			for bx in b.get("boxes", []):
				_fill(img, Rect2(float(bx[0]), float(bx[1]), float(bx[2]) - float(bx[0]), float(bx[3]) - float(bx[1])), S, one)
		else:
			_fill(img, r, S, one)
	var mx := int(bake.get("mx", 0))
	var my := int(bake.get("my", 0))
	for t in bake.get("trees", []):
		var px := (float(t[0]) + 0.5) * 16.0 + 1.0
		var py := (float(t[1]) + 1.0) * 16.0
		_fill(img, Rect2(px - 5.0, py - 4.0, 10.0, 5.0), S, one)
	return ImageTexture.create_from_image(img)

static func _fill(img: Image, r: Rect2, S: int, c: Color) -> void:
	var x0 := clampi(int(floor(r.position.x / S)), 0, img.get_width())
	var y0 := clampi(int(floor(r.position.y / S)), 0, img.get_height())
	var x1 := clampi(int(ceil(r.end.x / S)), 0, img.get_width())
	var y1 := clampi(int(ceil(r.end.y / S)), 0, img.get_height())
	if x1 > x0 and y1 > y0:
		img.fill_rect(Rect2i(x0, y0, x1 - x0, y1 - y0), c)

## Ground footprint of a baked block, in map px.
static func _foot(b: Dictionary) -> Rect2:
	match String(b.get("t", "")):
		"house":
			return Rect2(float(b.x0) - 1.0, float(b.wallBottom) + 1.0 - 22.0, float(b.x1) - float(b.x0) + 2.0, 22.0)
		"box":
			return Rect2(float(b.sx), float(b.sy) + float(b.h) - 5.0, float(b.w), 5.0 + 1.0)
		"card":
			return Rect2(float(b.sx), float(b.get("z", float(b.sy) + float(b.h))) - 3.0, float(b.w), 4.0)
		"cellboxes", "walls", "terrace":
			return Rect2(float(b.sx), float(b.sy), float(b.w), float(b.h))
	return Rect2()
