"""CI guard for the committed clipping report (pipeline/data/clipping_report.json).

char_clip.py needs Blender (bpy) and about a minute per character, so CI does not re-run it; it checks that the report
generated by the last pipeline run still meets the budget:

  * every character was tested,
  * static (rest-pose) penetrations stay under the per-character budget (what is left is hair locks / long hair on the shoulders),
  * animated penetrations (vertices that go through the body / another limb in any sampled frame of the 19 clips)
    stay under the per-character budget recorded in the report.

  python3 pipeline/blender/check_clipping_report.py [report.json]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = os.path.join(HERE, '..', 'data', 'clipping_report.json')


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    rep = json.load(open(path))
    budget = rep['budget']['animated_per_character']
    sbudget = rep['budget']['static_per_character']
    chars = rep['characters']
    manifest = json.load(open(os.path.join(HERE, '..', '..', 'godot', 'assets', 'models', 'characters', 'manifest.json')))
    bad = []
    missing = [k for k in manifest['sprites'] if k not in chars]
    for k, r in sorted(chars.items()):
        static = sum(r['rest'].values())
        anim = r['total']
        flag = static > sbudget or anim > budget
        print('%-18s rest=%d animated=%d worst=%s %s' % (k, static, anim, r['worst_mm'], 'FAIL' if flag else 'ok'))
        if flag:
            bad.append(k)
    print('SUMMARY characters=%d missing=%s failing=%s total_animated=%d budget=%d' % (
        len(chars), missing, bad, sum(r['total'] for r in chars.values()), budget))
    sys.exit(1 if (bad or missing) else 0)


if __name__ == '__main__':
    main()
